export EDITOR='mate -w'
export PS1='\w$(__git_ps1 " (%s)"):'
export PATH=/usr/local/bin:$PATH
export PATH="/usr/local/heroku/bin:$PATH"

source ~/.git-completion.bash
source ~/.chef/aliases

eval "$(rbenv init -)"
alias rtest='ruby -Itest'
alias zest='zeus test'
alias zake='zeus rake'

export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_HEAP_FREE_MIN=500000
