export EDITOR='atom -nw'
export PS1='\w$(__git_ps1 " (%s)"):'
export PROMPT_COMMAND='echo -ne "\033]0;${PWD/#$HOME/~}:\007"'

export PATH=/usr/local/bin:$PATH
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="./bin:$PATH"

source ~/.git-completion.bash
source ~/.chef/aliases
source ~/.zd.sh

eval "$(rbenv init -)"
alias rtest='ruby -Itest'
alias brake='bundle exec rake'

export JAVA_HOME=$(/usr/libexec/java_home)
