vim_plugin_task "autoclose",        "git://github.com/Townk/vim-autoclose.git"
vim_plugin_task "rails",            "git://github.com/tpope/vim-rails.git"
vim_plugin_task "ragtag",           "git://github.com/tpope/vim-ragtag.git"
vim_plugin_task "bundler"           "git://github.com/tpope/vim-bundler.git"
vim_plugin_task "abolish",          "git://github.com/tpope/vim-abolish.git"
vim_plugin_task "vim-css-color",    "git://github.com/skammer/vim-css-color.git"
