export EDITOR="/usr/local/bin/mate -w"

export PATH=/usr/local/bin:$PATH
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="./bin:$PATH"

eval "$(rbenv init -)"
eval "$(jenv init -)"
alias rtest='ruby -Itest'
alias brake='bundle exec rake'

export JAVA_HOME=$(/usr/libexec/java_home)

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
