export EDITOR="code -w"

# export PATH=/usr/local/bin:$PATH
# export PATH="./bin:$PATH"

alias rtest='ruby -Itest'
alias smash='git reset $(git merge-base main $(git rev-parse --abbrev-ref HEAD))'

export ZSH=$HOME/.oh-my-zsh
ZSH_DISABLE_COMPFIX=true
ZSH_THEME="robbyrussell"
plugins=(git textmate)
source $ZSH/oh-my-zsh.sh

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
